export const Permission = {
    COMPANY:{
        View:"View Company",
        CREATE:"create-company",
        UPDATE:"update_company",
        UPLOADCOMPANYDOCS:"upload_company_document",
        VERIFFYCOMPANYDOCS:"verify_company_document"
    },
    USER:{
        View: "view_user",
        CreateUser:"create_user",
        UpdateUser:"update_user",
        UploadUserDocs:"upload_user_document",
        VerifyUserDocs:"verify_user_document",
        DeleteUser:"delete_user"
    },
    DRIVER:{
        View:"view_driver",
        CreateDriver:"create_driver",
        UpdateDriver:"update_driver",
        UploadDriverDocs:"upload_driver_document",
        VerifyDriverDocs:"verify_driver_document",
        DeleteDriverDocs:"delete_driver"
    },
    VEHICLE:{
        View:"view_vehicle",
        CreateVehicle:"create_vehicle",
        UpdateVehicle:"update_vehicle",
        UploadVehicleDocs:"upload_vehicle_document",
        VerifyVehicleDocs:"verify_vehicle_document",
        DeleteVehicle:"delete_vehicle"
    },
    ROUTE:{
        View:"view_route",
        CreateRoute:"create_route",
        UpdateRoute:"update_route",
        DeleteRoute:"delete_route",
    },
    PARTY:{
        View:"view_party",
        CreateParty:"create_party",
        UpdateParty:"update_party",
        DeleteParty:"delete_party",
        ViewPartyGst:"view_party_gst",
        ViewPartyAddress:"view_party_address"
    },
     VEHICLEDRIVERASSIGN:{
        AssignDriverToVehicle:"assign_driver_to_vehicle",
        
        ViewAssignmentHistory:"view_vehicle_driver_assignment_history",
        ViewVehicleToDriver:"view_vehicle_driver_assignment",
        ViewCurrentVehicleToDriver:"view_current_vehicle_driver",
        ViewCurrentDriverToVehicle:"view_current_driver_vehicle",
     },
     JOB:{
        ViewJob:"view_job",
        CreateJob:"create_job",
        UpdateJob:"update_job",
        DeleteJob:"delete_job"
     },
     TRIP:{
        ViewTrip:"view_trip",
        CreateTrip:"create_trip",
        UpdateTrip:"update_trip",
        DeleteTrip:"delete_trip",
        ViewTripAdvance:"view_trip_advance",
        CreateTripAdvance:"create_trip_advance",
        ViewTripExpense:"view_trip_expense",
        CreateTripExpense:"create_trip_expense",
        UpdateTripExpense:"update_trip_expense",
        UploadTripPOD:"upload_trip_pod",
        ViewTripPOD:"view_trip_pod",
        VerifyTripPod:"verify_trip_pod",
        ChangeTripStatus:"change_trip_status"
     },
     DASHBOARD:{
        ViewDashboard:"view_dashboard"
     },
     DOCUMENT:{
        UploadDOCS:"upload_docs",
        VerifyDocs:"verify_docs",
        DocumentStatus:"documentStatus",
        DocumentUser:"documentUsers"
     }
};